image: node:18

stages:
  - build
  - deploy

build_job:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist

pages:
  stage: deploy
  dependencies:
    - build_job
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - dist
  publish: dist
  only:
    - main
